### PR TITLE
run npm install when deployed to Azure

### PR DESCRIPTION
**Pull request by watashiSHUN**

### CODE REVIEW

**Comment by skendrot** [comment]
Thanks! That did get NPM to install. Now it appears typescript is not playing nicely. Numerous build errors

**Comment by watashiSHUN** [comment]
I got that too when I was testing it locally, you can probably debug it in Visual Studio

**Comment by skendrot** [comment]
I haven't tested with these changes, but prior I was able to build the project without any problems

**Comment by watashiSHUN** [comment]
can you identify the working commit id?

**Comment by skendrot** [comment]
Building fine on my machine in both debug and release with the current source (looks like I did mess up tsconfig). Still failing with with kudu

**Pull request merged**
